### ISSUE TITLE
Unable to load dynamic library doing npm start

### ISSUE THREAD

**Issue by YashKumarVerma** [MorpheusAIs/Morpheus#554]
<img width="1440" alt="image" src="https://github.com/MorpheusAIs/Morpheus/assets/14032427/ad727c7e-2e20-4766-a8c5-6b5c651a0e7e">

Getting this error when trying to setup a local developer environment.

Mac: 14.2.1 (23C71)

### Logs
```
  Morpheus git:(main) npm run start

> morpheus@0.0.4 start
> electron .

2024-02-10 18:22:24.235 Electron[18621:11545396] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
Ollama server is running
Error: HTTP Error (500): {"error":"Unable to load dynamic library: Unable to load dynamic server library: dlopen(/var/folders/vd/0nngp7x525j4mv831pz446vw0000gn/T/ollama4108819979/metal/libext_server.dylib, 0x0006): tried: '/var/folders/vd/0nngp7x525j4mv831pz446vw0000gn/T/ollama4108819979/metal/libext_server.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/var/folders/vd/0nngp7x525j4mv831pz446vw0000gn/T/ollama4108819979/metal/libext_server.dylib' (no such file), '/var/folders/vd/0nngp7x525j4mv831pz446vw0000gn/T/ollama4108819979/metal/libext_server.dylib' (no su"}
    at Ollama.generate (/Users/yash/Desktop/yashkumarverma.com/github.com/Morpheus/src/service/ollama/ollama.js:286:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Ollama.run (/Users/yash/Desktop/yashkumarverma.com/github.com/Morpheus/src/service/ollama/ollama.js:177:5)
    at async run (/Users/yash/Desktop/yashkumarverma.com/github.com/Morpheus/src/service/ollama/ollama.js:329:10)
    at async IpcMainImpl.runOllamaModel (/Users/yash/Desktop/yashkumarverma.com/github.com/Morpheus/src/api.js:36:5)
^C/Users/yash/Desktop/yashkumarverma.com/github.com/Morpheus/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron exited with signal SIGINT
```

## Versions
- Node: v18.17.1
- NPM: 9.6.7

**Comment by DavidAJohnston** [comment]
This screen shot mentioned version 0.0.4 
I believe this issue has already been addressed in version 0.0.6.
See the Beta branch.
